## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Xmx1536M -Dkotlin.daemon.jvm.options\="-Xmx1536M" -XX:+UseParallelGC -XX:MaxMetaspaceSize\=1024M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8

android.experimental.testOptions.managedDevices.allowOldApiLevelDevices=true

# Gradle Performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AGP 9.0 backwards compat properties.
# Commented out because we've hopefully migrated to not need them anymore. Uncomment them if this broke something.
#android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
#android.usesSdkInManifest.disallowed=false
#android.uniquePackageNames=false
#android.builtInKotlin=false
#android.newDsl=false
#android.enableAppCompileTimeRClass=false

# TODO: check these
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true

# TODO: R8 stuff - figure out if I can let these be their defaults (true)
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false

# Suppress warning about enabling `android.dependency.excludeLibraryComponentsFromConstraints`.
# I can enable that later if I want to.
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false