name: Fastlane Validation
on:
  push:
    paths:
      - fastlane/**
  pull_request:
    paths:
      - fastlane/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          fastlaneDir: fastlane/metadata/android
          usePlayStoreLocales: false
